import '~/styles/globals.css'

import React from 'react'

import type { Metadata } from 'next'

import { fontInter } from '~/libs/fonts'
import { envSchema } from '~/libs/zod'

import { Header } from '~/components/Header'
import { Provider } from '~/components/Provider'

export const metadata: Metadata = {
  title: 'onlyCIDs',
  description: 'Generated by create next app'
}

interface RootLayoutProps {
  children: React.ReactNode
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  envSchema.parse(process.env)

  return (
    <html lang="pt-br" className={fontInter.variable} suppressHydrationWarning>
      <body>
        <Provider>
          <Header />

          <>{children}</>
        </Provider>
      </body>
    </html>
  )
}

export default RootLayout
